name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: build libwpe
        env:
          LIBWPE: libwpe-1.16.3
        run: |
          wget https://wpewebkit.org/releases/${LIBWPE}.tar.xz
          tar xvf ${LIBWPE}.tar.xz

          sudo apt update
          sudo apt install -y libegl1-mesa-dev libgles2-mesa-dev libxkbcommon-dev

          cd ${LIBWPE}
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja
          ninja
          sudo ninja install
          sudo ldconfig

      - name: build wpebackend-fdo
        env:
          WPEBACKEND_FDO: wpebackend-fdo-1.16.1
        run: |
          wget https://wpewebkit.org/releases/${WPEBACKEND_FDO}.tar.xz
          tar xvf ${WPEBACKEND_FDO}.tar.xz

          sudo apt update
          sudo apt install -y meson ninja-build libwayland-dev libepoxy-dev libglib2.0-dev

          cd ${WPEBACKEND_FDO}
          meson setup build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig

      - name: build woff2
        run: |
          sudo apt update
          sudo apt install -y libbrotli-dev

          git clone --recursive https://github.com/google/woff2.git
          cd woff2
          mkdir out
          cd out
          cmake ..
          make
          sudo make install
          sudo ldconfig

      - name: build libxslt
        env:
          VERSION: v1.1.43
          LIBXSLT: libxslt-v1.1.43
        run: |
          sudo apt update
          sudo apt install -y libxml2-dev

          wget https://gitlab.gnome.org/GNOME/libxslt/-/archive/${VERSION}/${LIBXSLT}.tar.gz
          tar xvf ${LIBXSLT}.tar.gz
          cd ${LIBXSLT}
          ./autogen.sh
          make
          sudo make install
          sudo ldconfig

      - name: build libbacktrace
        run: |
          git clone https://github.com/ianlancetaylor/libbacktrace.git --depth 1
          cd libbacktrace
          ./configure
          make
          sudo make install
          sudo ldconfig

      - name: build webkit
        env:
          WPEWEBKIT: wpewebkit-2.52.3
        run: |
          wget https://wpewebkit.org/releases/${WPEWEBKIT}.tar.xz
          tar xvf ${WPEWEBKIT}.tar.xz

          sudo apt update
          sudo apt install -y \
            g++ \
            gcc \
            libatk-bridge2.0-dev \
            libcairo2-dev \
            libgbm-dev \
            libgnutls28-dev \
            libharfbuzz-dev \
            libicu-dev \
            libxml2-dev \
            pkg-config \
            qt6-declarative-private-dev \
            unifdef \
            wayland-protocols \
            zlib1g-dev \
            libopenxr-dev \
            python3-psutil \
            libegl-mesa0 \
            libmount-dev \
            libopus-dev \
            libpulse-dev \
            libsrtp2-dev \
            libtheora-dev \
            libvorbis-dev \
            libvpx-dev \
            libxcb-glx0-dev \
            libxcb-xkb-dev \
            libxkbcommon-dev \
            libxrandr-dev \
            libxcb-cursor-dev \
            libportal-dev \
            libportal-gtk4-dev

          sudo apt install -y \
            libgcrypt20-dev \
            libgpg-error-dev \
            libsoup-3.0-dev \
            gobject-introspection \
            flite1-dev \
            libjxl-dev \
            libhyphen-dev \
            libavif-dev \
            libsystemd-dev \
            libdrm-dev \
            libseccomp-dev \
            bubblewrap \
            xdg-dbus-proxy

          sudo apt install -y \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            libgstreamer-plugins-good1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-pulseaudio

          sudo apt install -y python3-pip python3-venv
          python3 -m pip install --user gi-docgen

          cd ${WPEWEBKIT}
          cmake -DPORT=WPE -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja
          ninja
          sudo ninja install
          sudo ldconfig

      - name: notify
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_URL }}
          JOB_STATUS: ${{ job.status }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"ビルド結果: $JOB_STATUS\nリポジトリ: $GITHUB_REPOSITORY\nワークフロー: $GITHUB_WORKFLOW\nジョブ: $GITHUB_JOB\nコミット: $GITHUB_SHA\n詳細: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" \
          ${DISCORD_WEBHOOK_URL}
