name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: build libwpe
        env:
          LIBWPE: libwpe-1.16.3
        run: |
          wget https://wpewebkit.org/releases/${LIBWPE}.tar.xz
          tar xvf ${LIBWPE}.tar.xz

          sudo apt update
          sudo apt install -y libegl1-mesa-dev libgles2-mesa-dev libxkbcommon-dev

          cd ${LIBWPE}
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja
          ninja
          sudo ninja install

      - name: build wpebackend-fdo
        env:
          WPEBACKEND_FDO: wpebackend-fdo-1.16.1
        run: |
          wget https://wpewebkit.org/releases/${WPEBACKEND_FDO}.tar.xz
          tar xvf ${WPEBACKEND_FDO}.tar.xz

          sudo apt update
          sudo apt install -y meson ninja-build libwayland-dev libepoxy-dev libglib2.0-dev

          cd ${WPEBACKEND_FDO}
          meson setup build
          ninja -C build
          sudo ninja -C build install

      - name: build webkit
        env:
          WPEWEBKIT: wpewebkit-2.52.3
        run: |
          wget https://wpewebkit.org/releases/${WPEWEBKIT}.tar.xz
          tar xvf ${WPEWEBKIT}.tar.xz

          sudo apt update
          sudo apt install -y \
            g++ \
            gcc \
            libatk-bridge2.0-dev \
            libcairo2-dev \
            libgbm-dev \
            libgnutls28-dev \
            libharfbuzz-dev \
            libicu-dev \
            libxml2-dev \
            pkg-config \
            qt6-declarative-private-dev \
            unifdef \
            wayland-protocols \
            zlib1g-dev \
            libopenxr-dev \
            python3-psutil \
            libegl-mesa0 \
            libmount-dev \
            libopus-dev \
            libpulse-dev \
            libsrtp2-dev \
            libtheora-dev \
            libvorbis-dev \
            libvpx-dev \
            libxcb-glx0-dev \
            libxcb-xkb-dev \
            libxkbcommon-dev \
            libxrandr-dev \
            libxcb-cursor-dev \
            libportal-dev \
            libportal-gtk4-dev

          sudo apt install -y \
            libgcrypt20-dev \
            libgpg-error-dev \
            libsoup-3.0-dev \
            gobject-introspection \
            flite1-dev \
            libjxl-dev \
            libhyphen-dev

          sudo apt install -y python3-pip python3-venv
          python3 -m pip install --user gi-docgen

          cd ${WPEWEBKIT}
          cmake -DPORT=WPE -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja
          ninja
          sudo ninja install
